// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXeLjcp_1As1lK9qWpRtjM7XvoaoZg-YE',
    appId: '1:13037282170:web:559e82f3b4c2d237daacc3',
    messagingSenderId: '13037282170',
    projectId: 'invertale1',
    authDomain: 'invertale1.firebaseapp.com',
    storageBucket: 'invertale1.appspot.com',
    measurementId: 'G-41H3EE480Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu46O7VuFduWEGNkzW1XfsUhb8XhCT7dE',
    appId: '1:13037282170:android:160e2c4679e47718daacc3',
    messagingSenderId: '13037282170',
    projectId: 'invertale1',
    storageBucket: 'invertale1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqJbem-rdQ9xLS2uJXBF8nAhD_i-Hkuh8',
    appId: '1:13037282170:ios:a235a4b92f795478daacc3',
    messagingSenderId: '13037282170',
    projectId: 'invertale1',
    storageBucket: 'invertale1.appspot.com',
    iosBundleId: 'com.example.seProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqJbem-rdQ9xLS2uJXBF8nAhD_i-Hkuh8',
    appId: '1:13037282170:ios:a235a4b92f795478daacc3',
    messagingSenderId: '13037282170',
    projectId: 'invertale1',
    storageBucket: 'invertale1.appspot.com',
    iosBundleId: 'com.example.seProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXeLjcp_1As1lK9qWpRtjM7XvoaoZg-YE',
    appId: '1:13037282170:web:25d621cfdddbba90daacc3',
    messagingSenderId: '13037282170',
    projectId: 'invertale1',
    authDomain: 'invertale1.firebaseapp.com',
    storageBucket: 'invertale1.appspot.com',
    measurementId: 'G-5K48GR6L1X',
  );
}
