// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'key',
    appId: '1:276764865712:web:f835118d4f877c9e7d3775',
    messagingSenderId: '276764865712',
    projectId: 'inventale-bf5aa',
    authDomain: 'inventale-bf5aa.firebaseapp.com',
    storageBucket: 'inventale-bf5aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'key',
    appId: '1:276764865712:android:036af1a9418570c37d3775',
    messagingSenderId: '276764865712',
    projectId: 'inventale-bf5aa',
    storageBucket: 'inventale-bf5aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'key',
    appId: '1:276764865712:ios:18e8e2a049b89e687d3775',
    messagingSenderId: '276764865712',
    projectId: 'inventale-bf5aa',
    storageBucket: 'inventale-bf5aa.firebasestorage.app',
    iosBundleId: 'com.example.seProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'key',
    appId: '1:276764865712:ios:18e8e2a049b89e687d3775',
    messagingSenderId: '276764865712',
    projectId: 'inventale-bf5aa',
    storageBucket: 'inventale-bf5aa.firebasestorage.app',
    iosBundleId: 'com.example.seProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'key',
    appId: '1:276764865712:web:89f3b75cb7a7ee4a7d3775',
    messagingSenderId: '276764865712',
    projectId: 'inventale-bf5aa',
    authDomain: 'inventale-bf5aa.firebaseapp.com',
    storageBucket: 'inventale-bf5aa.firebasestorage.app',
  );

}